# Generated by Django 4.0.4 on 2022-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_socialmedia_email_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='insta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(max_length=50),
        ),
    ]
